# Generated by Django 3.0.4 on 2020-03-14 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=100)),
                ('todo_date', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
