# Generated by Django 3.0.4 on 2020-03-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20200314_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
