# Generated by Django 3.0.4 on 2020-03-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_new',
        ),
    ]
